### ISSUE TITLE
Add login option to vote

### ISSUE THREAD

**Issue by hidroh** [hidroh/materialistic#100]
Allow a user to enter his HN credentials to permit vote and comment.

**Comment by rasebo** [comment]
I would also like to see this feature implemented, it would make a great addition to an otherwise excellent app.

**Comment by aviaryan** [comment]
:+1: this is the only thing missing.

**Comment by hidroh** [comment]
I'll try to work out something for next release, but no promise though because without official support any solution now would be cumbersome.

**Comment by hidroh** [comment]
Gonna split this issue into smaller chunks so it's easier to track & release
