### ISSUE TITLE
Fix the progress bar for the PDF documents

### ISSUE THREAD

**Issue by astashov** [hidroh/materialistic#1012]
Hey @hidroh, I'd like to get approval on the approach, and then I'll implement it.

So, for now the progress bar for the PDF docs is confusing, because it really shows loading of the PDF loader HTML document, and then actual PDF document rendering. Those things are actually pretty fast, and the slow part (actual downloading of the PDF doc) is not reflected in the progress bar at all, so sometimes it seems that it's broken and the page not gonna appear.

So, we should implement it's own code path for the PDF progress bar - starting from `setDownloadListener`, where we figure out it's a PDF document, and til finish initializing the PDF document in PDF.js.

So, for example:

* In `setDownloadListener` we look at the mime type and figure out it's PDF - set progress to 10%
* Then we start download, and on download finish we set the progress to e.g. 80%
* Then we start sending the PDF doc to the WebView, and when there's enough data to start rendering the first page we set the progress to 100%.

But this approach will look for a regular user like this - the progress bar goes to 10%, then it stays there for a while - then quickly to 80% and quickly to 100% and gone.

Would be cool to update the progress bar while downloading the PDF document, but I kinda struggle figuring out how to do that. To track progress, we essentially need to add `OkHttpClient.Builder().addNetworkInterceptor` to the `Call.Factory` we use to download a file. But it seems pretty tricky to pass it to the provider in `NetworkModule`, and somehow get the values from it in `FileDownloader`. Any ideas how to do that?

So, what do you think? Would it be good enough to go with 10%-long-wait-80%-100% route, given edge-casey nature of PDF renderer, and that would give users enough understanding that it's still being processed and not broken. Or we should go with 10%-actual-download-progress-80%-100%, which provides better UX/UI, but tricker with implementation and adds more complexity?

Thanks!

**Comment by astashov** [comment]
Got the pull request for you to review: https://github.com/hidroh/materialistic/pull/1014 :)

**Comment by hidroh** [comment]
Good job! 👍

**Comment by astashov** [comment]
Thanks for merging this!
Well, this is kinda fun. I'd like to help more. Do you need more help? Any particular task you'd like to implement and could delegate to me?

**Comment by hidroh** [comment]
Thanks for contributing! There are a lot more standing issues but many of them would require some code restructuring first, otherwise it would be hard for the app to grow. You can skim through the list of open issues to see if any bug/feature request interests you and we can discuss a bit before you start 👍
