### ISSUE TITLE
AppCompatSpinner title text size

### ISSUE THREAD

**Issue by tjmille2** [hidroh/materialistic#1035]
How does one change the title text size on AppCompatSpinner (not the drop down item(s))? Google only references changing the drop down item size

**Comment by hidroh** [comment]
A Spinner takes a [`SpinnerAdapter`](https://developer.android.com/reference/android/widget/SpinnerAdapter.html) for its data source and item view binding logic. Inside this adapter class you should find 2 methods, `getView()` which controls the list view item (once you open the dropdown) and `getDropDownView()` which controls the dropdown view (once you collapse the dropdown)

**Comment by hidroh** [comment]
I'm closing this now since there's no actionable item for me.
