### ISSUE TITLE
Articles aren't loading in app any more

### ISSUE THREAD

**Issue by hidroh** [hidroh/materialistic#105]
Ever since the latest update, articles don't load any more. I have to click the open in browser button to be able to read it externally.

**Comment by kgurnani96** [comment]
weird, im trying to replicate this to try and fix it, but articles seem to be loading properly on my device (Sony xperia z3 d6603 android 5.1.1), can you give more info about how/when they don't load?

**Comment by hidroh** [comment]
This was logged by a user and forwarded as a Github issue. I should probably extract some information (device, OS etc) to include so in the future we can narrow down the issue.

For this issue though, I do notice some articles load in a funny way (e.g. not fit to screen, cannot pinch to zoom) but not sure if it's because of last update.

**Comment by kgurnani96** [comment]
i too notice pinch to zoom isn't working the way it should, im gonna try a previous version to see if it works

**Comment by hidroh** [comment]
It's probably due to `WebView` being put inside a `NestedScrollView` so that the header can be scrolled out of the screen.

**Comment by kgurnani96** [comment]
i think you are right, i'm new to android so i don't know a lot, but upon reading a bit, this may be of use https://github.com/ManuelPeinado/FadingActionBar

**Comment by hidroh** [comment]
Gonna close this. If this regresses please comment to reopen.
