### ISSUE TITLE
No way to share link with Chrome Custom Tabs

### ISSUE THREAD

**Issue by hidroh** [hidroh/materialistic#123]
It's impossible to share links when choose to open links in Chrome Customer Tabs (other than open link in Chrome then share from there).
Device: LGE Nexus 5, SDK: 23, app version: 23

**Comment by yegle** [comment]
Reporter here. Let me know if you need any clarification or follow up. Thank you for this awesome app.

**Comment by hidroh** [comment]
Sure I'll include this in next release. Current Chrome custom tab integration only customizes tab color but I plan to add share and comments button.
