### ISSUE TITLE
Cannot login anymore

### ISSUE THREAD

**Issue by naavis** [hidroh/materialistic#1314]
I've been using the Materialistic client for a long while. Today when I tried to upvote something, I got the login dialog. I tried entering my credentials and logging in but I just get the toast message 

> Validation required. If this doesn't work you can email

and nothing happens. I tried removing the account from my phone and reinstalling the client, but doesn't help.
My phone is a Nokia 8 with Android 9.

**Comment by blaueente** [comment]
It is the new recaptcha which you get when you login via website. This is plain evil.

**Comment by naavis** [comment]
That's a good point. I see the same message on the Hacker News login page.

**Comment by hidroh** [comment]
I have been informed that this is a temporary measure to prevent some attack. We can't do nothing until HN removes it unfortunately.

**Comment by naavis** [comment]
Thanks! Now it seems to work again.

**Comment by archon810** [comment]
It's happening again now.
