### ISSUE TITLE
text select feature

### ISSUE THREAD

**Issue by hidroh** [hidroh/materialistic#133]
sometimes selecting text does not work on some user comments but works on others. 
Device: LGE Nexus 5, SDK: 23, app version: 24

**Comment by hidroh** [comment]
Can't replicate this. I need more info/screenshot to investigate further.

**Comment by reactivize** [comment]
This is still happening quite frequently to me. It seems to be most reproducible on nested comments.
I can get it to sometimes work properly if I collapse and expand a nested comment.


I currently have a more immediate bug that has appeared within the last couple updates...
If I select some text, then click away, Materialistic will crash.

**Comment by hidroh** [comment]
Thanks I'll look into it. Linkified TextView seems to be quite troublesome. The select and click away crash seems to be a framework bug though: https://code.google.com/p/android/issues/detail?id=190507

**Comment by hidroh** [comment]
Similar framework bug: https://code.google.com/p/android/issues/detail?id=191430

**Comment by reactivize** [comment]
Ya good catch hidroh, and that workaround linked to on stackoverflow overriding dispatchTouchEvent might work until Android hopefully fixes the issue on their next OS update. What do you think?

http://stackoverflow.com/questions/33821008/illegalargumentexception-while-selecting-text-in-android-textview

**Comment by hidroh** [comment]
Yes I have seen that, but let me see if I can work around this with a cleaner approach.

**Comment by hidroh** [comment]
@reactivize for original selection bug, may I know what setting you are on? (single page collapsed/auto expand/multi page) And your device OS? (e.g. Marshmallow/Lollipop or earlier). Thanks.

**Comment by reactivize** [comment]
Sounds great on the cleaner approach. 
Also to note that the bug does not exist on the Article or the Readability screens, only on the Comments screen.

I am using the single page - auto expand setting.

For the " touch event won't even select text on some particular comments" bug, I just tried about 30 or so touch selections on comments text on a few different threads, and all is working fine, so am not able to reproduce it at the moment. It seemed to have gone away about two updates ago when the 2nd bug arrived. But I'll keep an eye out for it. (I'm not fully convinced it's gone.)

One man's opinion... 
In settings, I'd put a checkbox toggle to turn on or off the text selection feature, and probably have it deselected by default. 
Reasoning... 
a subset of people probably don't select text as part of their usage behavior with the app and it can be a UX irritation when one lays their finger or thumb on the screen and the selection handle pops up, when they have no intention of actually doing a selection.

I myself select text all the time, for a number of reason, including...
- taking notes on debate topics to research further
- collect cool words or expressions
- dictionary searches of terms
- to verify citations by googling phrases
- to remember a concept, where it's not worth bookmarking the whole thread.
- probably some other reasons too I can't think of at the moment.

p.s.
great app. I've tried pretty much all the other HN apps in the Android app store, and this one is a few steps ahead, and getting better.  :+1:

**Comment by hidroh** [comment]
Article & readability use a web view to render so they do not suffer the same issue.

For text selection toggle option, I'll think about it. If only Android have iOS's 3D touch lol. Probably will have a selection lock on comments tab, the settings section is getting a bit crowded now.

Thanks for your support, keep the feedback coming!

**Comment by reactivize** [comment]
I downloaded the latest update yesterday and used the app for about an hour or two and the selection feature has been working perfectly. At this time I consider these two bugs resolved, at least in terms of my usage of it. Great work! The app is a joy to use.

**Comment by hidroh** [comment]
Gonna close this, if this regresses we'll reopen.
