### ISSUE TITLE
Allow disabling or lazy-loading the readability tab

### ISSUE THREAD

**Issue by tdryer** [hidroh/materialistic#159]
The new readability tab seems to load the web page in the background as soon as the comments activity is opened. It would be nice to have an option to disable it or only load it when the tab is selected in order to avoid unnecessary data usage when using a metered connection.

**Comment by hidroh** [comment]
I'll add a 'save data' option to allow choosing loading all tabs at once, or only load the active one. We can also have an 'auto' option that will monitor connectivity and load all tabs on wifi http://developer.android.com/training/monitoring-device-state/connectivity-monitoring.html

**Comment by tdryer** [comment]
That's perfect, thanks!
