### ISSUE TITLE
remember which external browser was selected 

### ISSUE THREAD

**Issue by hidroh** [hidroh/materialistic#204]
It'd be great if when using an external browser to open links, the app remembers which browser I chose. Right now I need to choose again each time I tap a link, which makes the feature somewhat useless. Thanks! 
Device: samsung SM-G920T, SDK: 22, app version: 34

**Comment by hidroh** [comment]
Probably have to ditch `ACTION_CHOOSER` Intent and go for a custom bottom sheet UI, as there are no ways to customize system UI for chooser to inject a 'select as default' option.

https://github.com/Flipboard/bottomsheet

**Comment by joshsharp** [comment]
Could you use `ACTION_VIEW` and just open links in the default browser/app?

**Comment by hidroh** [comment]
It used to be `ACTION_VIEW`, then switched to `ACTION_CHOOSER` as I need to exclude Materialistic from list of apps handling HN links, but you are right, I can make an exception for HN links, and use `ACTION_VIEW` for other links.
