### ISSUE TITLE
Run robolectric Unit Test failed

### ISSUE THREAD

**Issue by Harlber** [hidroh/materialistic#209]
I got error while running Unit Test based on these document. 
- http://robolectric.org/getting-started/
- http://tools.android.com/tech-docs/unit-testing-support

And error shows like this:
<img src="http://i12.tietuku.com/c0fc7608ee7674b5.png" width="300px" />

How can I run these tests successfully
<b>Thanks in advance!</b>

**Comment by hidroh** [comment]
I has been a while since I last tried running test directly in Android Studio. It should run via command line though (otherwise travis wouldn't be able to build).

May I know which version of Android Studio you are using? And which OS (Mac OS X/Windows/Linux)?

**Comment by Harlber** [comment]
Windows &  Android Studio 1.3.2 .Thanks a lot.

**Comment by hidroh** [comment]
If this is blocking for you you may want to try the latest Android Studio 2.0, though it's not yet stable and still in dev channel. You can have both current AS and AS2 installed though.

With AS2 you no longer have to specify test artifacts. It's also easier to run individual tests. I'm using AS2 and run just fine.

http://android-developers.blogspot.sg/2015/11/android-studio-20-preview.html

**Comment by Harlber** [comment]
Copy that.Thanks a lot for your time.I will try your suggestion as soon as possible.
PS
I've been using materialistic which build myself.And I also have many friends around the use of materialistic.So I forked materialistic and prepare to pull request in a few days (support for <b>Simplified Chinese</b>)Do you have this similarly plan yet?If so,I will cancel my branch.Thanks  in advance!

**Comment by hidroh** [comment]
I will need to clean up translatable resources first. There are also a few coming changes to English text so you may want to hold your PR a bit. I suggest to close this issue and log a separate one for translation if you're keen. Thanks!

**Comment by Harlber** [comment]
Copy that .Thanks a lot.
