### ISSUE TITLE
how do you realize loading data asynchronously  in ListFragment ?

### ISSUE THREAD

**Issue by Chen-Sir** [hidroh/materialistic#21]
Hello  hidroh ,  I am an Android learner ,  I  have read your code of the project, but I didn't understand how you realize loading data asynchronously  in ListFragment . Can you  tell me about it ?  I will appreciate you sincerely !

**Comment by hidroh** [comment]
The idea is to let `RecyclerView` signals you when you need to load data.

We first make a network call to `v0/topstories.json` to fetch all the IDs and create an array of items with no data and set it as data source for `RecyclerView.Adapter`.

Whenever `RecyclerView` needs to display an item it will trigger `RecyclerView.Adapter.bindViewHolder()`, at which point you make another network call to `v0/item.json` to fetch the item (if not yet), or bind from previously fetched item. You'll need to write logic to decide whether to fetch an item again.

**Comment by Chen-Sir** [comment]
OK , thank you .   I read the code again  and  understand it.

**Comment by hidroh** [comment]
Ok so I will close this issue.
