### ISSUE TITLE
Share from Chrome Custom Tabs result in null title

### ISSUE THREAD

**Issue by hidroh** [hidroh/materialistic#210]
For apps that support sharing link with a title (Fenix the twitter client is the only one on my phone that support sharing link along with title)

So when you share a link from thr app to Fenix, you'll get the following text in a compose screen:

null - http://techcrunch.com/2015/12/08/mozilla-will-stop-developing-and-selling-firefox-os-smartphones/

While sharing from Chrome to Fenix for the same page, you'll get this:

Mozilla Will Stop Developing And Selling Firefox OS Smartphones | TechCrunch - http://techcrunch.com/2015/12/08/mozilla-will-stop-developing-and-selling-firefox-os-smartphones/

Device: LGE Nexus 5, SDK: 23, app version: 35

**Comment by yegle** [comment]
Feedbacker here. Sharing from non-Chrome Custom Tabs does have a correct title
