### ISSUE TITLE
Support offline reading

### ISSUE THREAD

**Issue by hidroh** [hidroh/materialistic#293]
I see that materialistic has to redownload the feeds everytime i close the app and reopen it. I would like it to store feed data and refresh only at my will. 
Device: Xiaomi 2014818, SDK: 19, app version: 39

**Comment by reactivize** [comment]
This would be a cool feature. What would also be nice if possible is if after an update of the app, I don't lose the thread I was on. Currently an app update from the App Store reloads the main thread list page on first viewing, so I lose what thread I was on.

**Comment by hidroh** [comment]
I'll consider both for future update.

**Comment by nikolowry** [comment]
As a subway rider - the best place to read is when I'm stuck underground. Was going to request an offline mode - but I'll just add it to this ticket

**Comment by hidroh** [comment]
@nikolowry may I know for you which one is more important to be available offline: a story's article or comments?

**Comment by nikolowry** [comment]
Sorry for a late reply - but the article is most important. Only plan to comment when a network connection is available

**Comment by hidroh** [comment]
Okay. I'm gonna implement offline support for comments and readability first, since there are already infrastructure to do caching. For actual web content like articles it's more tricky, so probably would do it in the next round.
