### ISSUE TITLE
Add "Best" section

### ISSUE THREAD

**Issue by azizLIGHT** [hidroh/materialistic#3]
I know you added the other sections recently, and I was hoping the "Best" list made it on the update but it didn't make it. Is it possible to add this section? It's nice to be able to read old thread with good information. 

Thanks

**Comment by hidroh** [comment]
Unfortunately I will not be able to fulfil this as there is no ready-made API to 'rank' stories. The other sections are only made available thanks to an update from official Hacker News API. However there is a search functionality coming up, maybe it would be of some help to you when in need to check old articles.

I'll be closing this, thanks for your support.
