### ISSUE TITLE
FATAL EXCEPTION: OkHttp Dispatcher

### ISSUE THREAD

**Issue by Harlber** [hidroh/materialistic#352]
Log shows like this:
![okhttp](https://cloud.githubusercontent.com/assets/7955320/12370205/e7a1aff4-bc42-11e5-9ace-b6aa87483491.png)

**Comment by hidroh** [comment]
Hi what Android version are you using? Is this on master, or a tagged version?

**Comment by Harlber** [comment]
yes,master,I forked yesterday！

**Comment by hidroh** [comment]
And what Android version caused the crash?

**Comment by Harlber** [comment]
Moto g , Android 5.0.2.
Btw,okhttp 3.0.1 is available now

**Comment by hidroh** [comment]
Again!? I just updated to 3.0.0-RC1 then 3.0.0. Thanks for informing me.

For the crash I'm not sure, may be something to do with multi threading, I need to take a look. Does this happen frequently?

**Comment by floating-cat** [comment]
https://github.com/square/retrofit/issues/1475

**Comment by hidroh** [comment]
Thanks @floating-cat
