### ISSUE TITLE
Status bar drop shadow sometimes disappears

### ISSUE THREAD

**Issue by tdryer** [hidroh/materialistic#366]
Very minor issue: the status bar drop shadow sometimes disappears. It seems to happen randomly while scrolling, but a reliable way to trigger it is to lock and unlock the screen.

Shadow:

![shadow](http://i.imgur.com/cPq0DqS.png)

No shadow:

![no shadow](http://i.imgur.com/4zWRDXA.png)

**Comment by hidroh** [comment]
Could be an AOSP bug, I logged an issue here http://b.android.com/199968

**Comment by hidroh** [comment]
Confirmed AOSP bug, should be fixed once they roll out an update.
