### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by alexanderadam** [hidroh/materialistic#368]
Hey @hidroh,

woah. Materialistic looks really good!
I wasn't able to find it [in the F-Droid database](https://f-droid.org/repository/browse/?fdfilter=materialistic&fdpage=1&page_id=0) though.
Would you mind [publishing it on the F-Droid catalogue](https://f-droid.org/contribute/#post-1182) ?

Thank you for your work!

Disclaimer: I have no idea how to publish something on F-Droid.

**Comment by hidroh** [comment]
Thanks, this issue has been raised before in #23, but I'm happy to keep it in just Play Store at the moment. It's open source with build instruction so anyone can make a build anyway.
