### ISSUE TITLE
quicker access to share icons

### ISSUE THREAD

**Issue by nMustaki** [hidroh/materialistic#41]
Hi,

First thanks you very much  for your work!
I use materialistic daily and I often share links, but I think sharing could be improved by :
- remembering the top share methods
- provide a quick access to the first 3 as a row in the top right menu
- maybe the first one should always be visible ?

What so you think?

**Comment by hidroh** [comment]
Hi thanks for supporting. If I'm not wrong this should be the default behaviour already (top share methods & the last share method as an icon that is visible). What Android version are you using?

**Comment by nMustaki** [comment]
I have Materialistic v1.4 on a Motorola Moto G 4G 2014 with Android 5.1.

On an article view, the top bar only contains the title and the dot menu.
Clicking on the latter open another menu with "save story / comments / View
in external browser / Share this story via".

Is there some configuration option I should check ?

Thanks


--
/*
** "What do you despise? By this you are truly known."
**	from Manual of Muad'Dib by the Princess Irulan.
*/

**Comment by hidroh** [comment]
Oh I see what you mean now. I will make a change to make share option visible if have room on title bar.

**Comment by nMustaki** [comment]
Great !


--
/*
** "What do you despise? By this you are truly known."
**	from Manual of Muad'Dib by the Princess Irulan.
*/
