### ISSUE TITLE
Add 'find in page' function for articles

### ISSUE THREAD

**Issue by hidroh** [hidroh/materialistic#412]
It would be helpful if you add a function to search for keywords in an article. 
Device: XOLO Q800, SDK: 17, app version: 44

**Comment by hidroh** [comment]
This can be tricky to implement, as articles are only cached and fetched on demand, and as such search results may be incomplete. But we can modify current saved stories search to include cached readability articles as well.

**Comment by s4chin** [comment]
Hi, this issue was made by me. I didn't want to search in all the articles.
When the article is loaded, I want a search function in the 'article' tab or the 'readability' tab. Will that be possible?

**Comment by hidroh** [comment]
Like a 'find in page' functionality? It can be done, but I need to find a place to squeeze in the search widget; current page is already full of options.

**Comment by hidroh** [comment]
We can use a [`FindListener`](https://developer.android.com/reference/android/webkit/WebView.html#setFindListener(android.webkit.WebView.FindListener)) for this.

**Comment by hidroh** [comment]
We'll just do a simple find all for the first iteration, as jumping between matches would need some extra work on layout.
