### ISSUE TITLE
Implement data backup

### ISSUE THREAD

**Issue by hidroh** [hidroh/materialistic#422]
can you please enable it for your app to backup app settings?
Device: Huawei Nexus 6P, SDK: 23, app version: 48

**Comment by hidroh** [comment]
This should already be handled automatically from Marshmallow, but lower versions will need custom implementation:

- http://developer.android.com/guide/topics/data/backup.html
- http://developer.android.com/training/backup/autosyncapi.html

**Comment by ShikherVerma** [comment]
I recently changed phone and had to manually transfer all the saved stories. There could be an import export option to export settings, saved stories to xml. I would like to contribute this feature. @hidroh plz give me a head start about where to begin.

**Comment by hidroh** [comment]
I prefer to keep this feature small and simple, as I'm planning something further than this, e.g. allow syncing data across multiple devices for the same user. For this feature only, we can have a section in Settings, where users choose to import/export their current data to/from file. We would need file storage permission pre Marshmallow for this.

**Comment by hidroh** [comment]
Merged into #538
