### ISSUE TITLE
Font size settings don't work on all devices

### ISSUE THREAD

**Issue by jottr** [hidroh/materialistic#430]
`Materialistic Version 2.5` 

Tested on 
```
Samsung Galaxy Tab SM-T715
Android Version 5.0.2
```
and 
```
HTC ONE M8 GPE 
Android 6.0
```
While setting the font size on the HTC works, it does not on the Galaxy Tab. 
I've tried to reinstall Materialistic, which did not remove the issue.

**Comment by hidroh** [comment]
Hi, thanks for taking time reproducing the issue. This has been reported in #398 and resolved in 2.6 release, which is currently under limited release (to 20% of users). I will soon make it available to all users.

**Comment by jottr** [comment]
Ok, sorry for the duplicate issue. 
Have you considered releasing builds as apk as well?

**Comment by hidroh** [comment]
Right now no, but I guess it can be done via build script to make snapshot APK for each tag. But the snapshot APK would not be compatible with the play store version though, as that version contains some private code and uses different signing key.
