### ISSUE TITLE
Submit PR for ShadowSupportDrawerLayout to Robolectric

### ISSUE THREAD

**Issue by jaredsburrows** [hidroh/materialistic#433]
Your Shadow:
https://github.com/hidroh/materialistic/blob/master/app/src/test/java/io/github/hidroh/materialistic/test/ShadowSupportDrawerLayout.java

Robolectric's version:
https://github.com/robolectric/robolectric/blob/master/robolectric-shadows/shadows-support-v4/src/main/java/org/robolectric/shadows/support/v4/ShadowDrawerLayout.java

Your shadow helped me, you should make a PR to the Robolectric repo :+1:

**Comment by hidroh** [comment]
@jaredsburrows I did submit it robolectric/robolectric#2317, but after discussion and long waiting I closed it.

**Comment by jaredsburrows** [comment]
@hidroh Sorry about that. I really wish they would move faster. If I was a collaborator I would read the PRs more often and make releases more often. Anyways, your code has help me. :) Thanks.

**Comment by hidroh** [comment]
@jaredsburrows No problem, I had planned to publish a collection of my shadows, but then I realized they are to specific, plus many of them may be obsolete by the time 3.1 released, so I just gave up. They are not that hard for one to come up with anyway.
