### ISSUE TITLE
Request: Alternatives to Google Play for downloading releases

### ISSUE THREAD

**Issue by nikolowry** [hidroh/materialistic#434]
Is there anyway you could upload the apks here in a release tag or possibly even distribute to /aptoide?

Not a Google Play user and I've constantly searching all day for the latest release on apkmirror/apk4fun with no luck (really want the new offline support!)

Regardless, thanks for the app and worst case I'll just check out the repo and start building myself.

**Comment by hidroh** [comment]
I added APK to latest tag. I don't have plan to upload to other stores though. But I'll continue attaching APK to each tag going forward so at least we have an alternative place to get APK.

Please leave me some feedback later once you have tried offline mode. Thanks!

**Comment by nikolowry** [comment]
Dope!!!!

**Comment by johanson** [comment]
What about making them available on (F-Droid)[https://f-droid.org/], since this project is FOSS anyway? It's also possible to download the APK's directly from their website in addition to their client.

**Comment by hidroh** [comment]
Hi thanks for supporting my app, but I don't have plan to publish on F-Droid.
