### ISSUE TITLE
[regression] Comment text area acts like a single line

### ISSUE THREAD

**Issue by cyphar** [hidroh/materialistic#443]
In previous versions, the comment text area acted like a proper text area. The keyboard supported newlines and the lines were wrapped in the view. In the latest version, this is no longer the case and it makes composing comments impossible (you can't add newlines).

**Comment by hidroh** [comment]
Thanks for reporting. I'll add a fix.

**Comment by hidroh** [comment]
Fixed. Should be available when I publish new version some time later this week.
