### ISSUE TITLE
Replace SyncAdapter with JobScheduler?

### ISSUE THREAD

**Issue by hidroh** [hidroh/materialistic#450]
Using [evernote/android-job](https://github.com/evernote/android-job) wrapper library.

**Comment by eku** [comment]
Why not RxJava?

**Comment by hidroh** [comment]
If I understand correctly they are 2 different things. RxJava is for reactive async event handling, which is meant to replace things such as async callbacks, local broadcast. JobScheduler/SyncAdapter is for scheduling background services (not necessarily doing any callbacks/broadcasts).
