### ISSUE TITLE
Show WebView of the article before the page is fully loaded

### ISSUE THREAD

**Issue by johanson** [hidroh/materialistic#453]
The loading bar is nice, but why not show the WebView instantly? Right now, you have to wait until **all** the assets are loaded. Some third-party scripts and trackers take forever to load, why not use the same method as in traditional web browsers, and show what's loaded already? The majority of the things are being loaded in parallel, text is the most important and is ready fairly quickly.

It makes the experience much faster, especially on painfully slow data connection.

Probably setting the visibility from `GONE` to `VISIBLE` in [WebFragment.java](https://github.com/hidroh/materialistic/blob/master/app/src/main/java/io/github/hidroh/materialistic/WebFragment.java#L113) is enough. Then there's no point in waiting for `newProgress` to reach 100 and setting it `VISIBLE`.

**Comment by hidroh** [comment]
Thanks, I think you're right. I remember setting it up that way because I don't want the website background to flash before it's fully loaded. I'll check to see if I can remove this behaviour.
