### ISSUE TITLE
Allow reloading web view if cache deleted

### ISSUE THREAD

**Issue by ShikherVerma** [hidroh/materialistic#456]
If cache is not present then app should reload the story from the website. Currently is just shows all the stories but on opening it is blank. might be related to #448 maybe cache is the problem there too.

**Comment by hidroh** [comment]
Hi is this WebView content you are referring to, or comments/readability? I'll probably add a pull to refresh so one can manually refresh WebView if they want fresh content.

**Comment by ShikherVerma** [comment]
All of them actually. In which class do I have to add it. Would like to contribute pull to refresh feature.

**Comment by hidroh** [comment]
Check `WebFragment`. `WebSettings` cache mode should be changed to `LOAD_NO_CACHE` upon refreshing.

**Comment by ShikherVerma** [comment]
I tried what you suggested but it didn't work. ![anim](https://cloud.githubusercontent.com/assets/10194699/15277039/76cb4ab4-1b16-11e6-9d16-7fb5ba868291.gif)

**Comment by hidroh** [comment]
Oh sorry this is a different issue. It's because the item being fetched regardless of network connection, and only upon item fetched then WebView would start to load from cache, which never happens. I'll fix this myself.

**Comment by ShikherVerma** [comment]
So should I close #457 
Doesn't seem relevant now

**Comment by hidroh** [comment]
@ShikherVerma well even though not really related to this, it's something good to have, if you have spare time to continue with it then please go ahead, otherwise you can close.

**Comment by hidroh** [comment]
Probably bundle the refresh control together with search control in #412

**Comment by hidroh** [comment]
@ShikherVerma real sorry but I think I'll not go ahead with this. With recent changes in the way WebView loads, it will always rely on network in case there is a cache hit. We only force load from cache if you have no connection, in which case a refresh is useless anyway. So I can't find a scenario where you need to manually refresh the page.
