### ISSUE TITLE
About Snackbars

### ISSUE THREAD

**Issue by Harlber** [hidroh/materialistic#46]
Snackbars was better used with FAB(CoordinatorLayout),and Retrofit 2.0.0beta is aviliable .
Opps,I was recently working on this project(https://github.com/Harlber/Moose) reference a lot from materialistic.Thanks a lot.

**Comment by hidroh** [comment]
As my app currently has no FABs, the Snackbars are just simply a slight improvement over Toasts in terms of allowing undo functionality.

**Comment by hidroh** [comment]
Btw, nice app you've got there!

**Comment by Harlber** [comment]
copy that

**Comment by Harlber** [comment]
In fact, I got some confusion in Material Design.Btw,in future versions,would consider joining FAB and other MD widget?

**Comment by hidroh** [comment]
I don't have any functionalities that require FAB. I consider FAB mostly for content creation, in which case the app has none at the moment. The other use case is to add a FAB to favorite items. But judging from how many people actually use it, it doesn't seem to be a very important feature.

Apart from that, I'm considering using `AppBarLayout` and `CollapsingToolbarLayout` to compact the `Toolbar`, but the interaction seems to conflict with `SwipeRefreshLayout`.

**Comment by Harlber** [comment]
Yes,it seems that the Design Library still has bugs in the last version..Maybe this blog can help you.
http://chris.banes.me/  Btw, I will be interested to learn materialistic.
