### ISSUE TITLE
Use the floating action button to add functionalities

### ISSUE THREAD

**Issue by nMustaki** [hidroh/materialistic#481]
Hi,

first thanks for Materialistic, I love it !
Since the floating action button is always visible, it would be great if it could have more functionalities, for instance, "go to top". My current grip is that I often scan through the 300+ first entries, and I would love a button to go back to the first one. I have the same issue with comments.

Thanks again,
Nathan

**Comment by hidroh** [comment]
@nMustaki you can tap the toolbar for a quick return to top (in list of stories), or tap any of the tab to scroll current page to top (in comments, article or readability).

For other functionalities I'm thinking of putting in a 'find in page' control for article/readability, as requested in #412

**Comment by hidroh** [comment]
If you enable volume navigation in settings, you can long press volume up to scroll current page back to top as well.

**Comment by nMustaki** [comment]
I hadn't noticed that, thanks !
Find in page would be great too :-)
