### ISSUE TITLE
Headlines truncated

### ISSUE THREAD

**Issue by Bit32** [hidroh/materialistic#5]
It seems to me the ability to read a headline in its entirely is of critical importance, particularly when the link title is the only information you have to go on before deciding on whether to click through and view a site.

Currently Materialistic feels almost claustrophobic in its handling of Headlines - particularly when switching between it and other Hackernews clients.

This could be improved simply by making the headline font size smaller. Alternatively making box height variable so as to incorporate the full headline would resolve this issue entirely.

**Comment by hidroh** [comment]
Thanks for your support. I'm aware of this problem and have tried to mitigate it by allowing full title display in comment view, though it still requires opening an item.

The headline font size is a design choice, while fixed item size allows smooth scrolling. I'm planning to implement an option to choose font size, maybe it will help. Otherwise a convenient fix would be to increase item's height to accomodate more lines, or simply make height variable like you suggested.

**Comment by Bit32** [comment]
Cheers for the response and appreciate hearing some background to your decisions - interesting that the fixed box size makes a noticeable difference to the scrolling. 

Did look for a setting to change the font size so that could definitely help. Another option you might want to consider for smaller screen sizes is reducing the red comments icon size slightly and positioning it slightly lower, in line with the website and date lines. That would enable the headline to fill the space over to the right, adding space for another 10 or so characters.

Ps. Materialistic is a truly great app. Nice work :+1:

**Comment by tsuharesu** [comment]
One idea: https://github.com/grantland/android-autofittextview

Another idea: remove the author, date, etc. and put this info only on the Article View/ Comment view. I think the most important information for users is the Title of the Article.

Another idea [2]: don't use cards, instead use a list. Per Material Design guidelines, a card is only important to use when it has actions associated with them. Presenting a list information (like a list of Articles) should do better using a list (http://www.google.com/design/spec/components/cards.html)

**Comment by hidroh** [comment]
Thanks for suggestions. I prefer to keep the text size consistent though. I think I'll go with variable height, it doesn't look too bad anyway. For card view I have been pondering for a while whether I should drop it. I originally use it just to experiment with the new elevation attribute in SDK 21.

**Comment by hidroh** [comment]
Fixed by 5ed38a2375f99d3575f4e88b0e2d5d4e8b2c9f2d
