### ISSUE TITLE
Comment tab not updating comment count

### ISSUE THREAD

**Issue by reactivize** [hidroh/materialistic#553]
Great work on the app hidroh.

quick bug...
In the Comments view, if I refresh, the "X COMMENTS" counter isn't updating when new comments are loaded in.

For example, for me, the actual comment count went from 2 to 15 after refreshing, but it still read "2 COMMENTS" in the tab header.

**Comment by hidroh** [comment]
Thanks for reporting, I'm aware of this some time ago but keep forgetting to fix it.
