### ISSUE TITLE
Mark posts as read by scrolling

### ISSUE THREAD

**Issue by shadyvb** [hidroh/materialistic#558]
Currently there is no way to know where I ended up last time I opened the app, and there is no visual clue on what posts are new versus what I've read before ( talking about titles, not opening the post page itself ).

It'd be great if we can implement a way to mark items as read by scrolling, just like Feedly does now, so you can storm through issues and be sure not to miss anything important. Or maybe a `new` flag to flag newer post since the last application run.

**Comment by hidroh** [comment]
Are you using external browser + custom Chrome tab option?

**Comment by shadyvb** [comment]
Hmm, I don't use the external browser unless I want to share, mostly the readability view, but not sure if that's relevant to the feature I'm proposing, since it is concerns the list view.

**Comment by hidroh** [comment]
Read indicator has been implemented long time ago. As soon as you click a list view item its title will grey out (or apply appropriate disabled color for the theme you set).

**Comment by shadyvb** [comment]
Yup, that a great feature, but what I'm looking for is an indicator for 'I've seen this title before, but I'm not interested in reading the post, and I don't want to ask myself the same question again'.

Feedly app has a great demo on the feature, if you'd like to check it out.

**Comment by hidroh** [comment]
If you are using latest version, you can enable 'Highlight updated stories' and set Default screen to 'Last used screen'. This way when you come back to the app, the list shows an outdated list, and upon refreshing (via pull to refresh), you will see indicators of which stories are new, promoted or have new comments.

I'll consider adding 'mark as read as you scroll' option as well.

**Comment by shadyvb** [comment]
Yes, `mark as read as you scroll` would be what I'm looking for. Thank!
