### ISSUE TITLE
Add post title when sharing 

### ISSUE THREAD

**Issue by shadyvb** [hidroh/materialistic#559]
It is a bit annoying to not be able to share a post from the app and have the post title in there, currently it only sends the URL, so I have to open in external browser and share from there.

**Comment by hidroh** [comment]
May I know from what screen you are sharing? Is it from custom Chrome tab?

**Comment by shadyvb** [comment]
Mostly readability, and Thanks for the quick reply!

**Comment by hidroh** [comment]
And which app you are trying to share to that exhibit this behavior? I normally test with Google Keep/Email and it seems to carry title.

**Comment by shadyvb** [comment]
Twitter / FB, never tried email nor Keep.

**Comment by hidroh** [comment]
Ok got it. I'll combine title + url for apps that don't support a title field.

**Comment by shadyvb** [comment]
Perfect! Thanks!
