### ISSUE TITLE
Swiping cards

### ISSUE THREAD

**Issue by shadyvb** [hidroh/materialistic#560]
One feature I'd be totally interested in would be the ability to swipe cards in either directions to:
- Flag || Mark as interesting || Will read later
- Share to Default Sharing service

Swiping cards is supported in the saved items view, so hopefully this would be much to implement.

**Comment by shadyvb** [comment]
Thanks for the speedy implementation, hoping to have this on my phone soon. When do you normally make a release ?

**Comment by hidroh** [comment]
Usually during weekend. If I have more stuffs to put in I may delay it a bit.
