### ISSUE TITLE
Images broken in readability mode

### ISSUE THREAD

**Issue by shadyvb** [hidroh/materialistic#565]
It has been a while since I saw images working in readability mode, used to work but got broken a few releases back. It does not work unless you open the article view, back to list, then back to readability view.

Steps to reproduce:

1. Open an article with an image in readability mode, images are broken
2. Open the Article tab, everything works
3. Go back to list view
4. Open the same article again, in readability mode, images work now

**Comment by hidroh** [comment]
Seems to be happening due to cache control
