### ISSUE TITLE
Disable pinch zoom when not in fullscreen

### ISSUE THREAD

**Issue by arcresu** [hidroh/materialistic#577]
In the article view, trying to pinch zoom usually results in the view scrolling. Using a very slow pinch zoom gesture I can get it to work half of the time, but the scrolling behaviour seems much more sensitive. Is there a way to prevent zoom and scroll from competing to interpret the same gestures?

**Comment by hidroh** [comment]
Can you try in fullscreen mode (by pressing the bottom right red button)? The current way the UI is structured makes it really hard to have good gesture support, unless the article view is standalone by itself, which is why I created fullscreen mode.

**Comment by arcresu** [comment]
Yes, you're right that the full screen mode fixes things. Maybe it would be better to disable the pinch zoom gesture in the non-full screen view though? The current situation makes it feel a bit broken since it kind of works but not really.

**Comment by hidroh** [comment]
Thanks for the suggestion. Let me see if I can disable some of the broken gestures.
