### ISSUE TITLE
Crash when doing shared element transition with long text content

### ISSUE THREAD

**Issue by hidroh** [hidroh/materialistic#6]
App crashed if return transition involves an element with long content that exceeds the max dimensions supported by GPU.
```
OpenGLRenderer  W  Layer exceeds max. dimensions supported by the GPU (984x4532, max=4096x4096)
AndroidRuntime  E  FATAL EXCEPTION: main
AndroidRuntime  E  Process: io.github.hidroh.materialistic, PID: 1632
AndroidRuntime  E  java.lang.IllegalStateException: Unable to create layer for CardView
AndroidRuntime  E  at android.os.MessageQueue.nativePollOnce(Native Method)
AndroidRuntime  E  at android.os.MessageQueue.next(MessageQueue.java:153)
AndroidRuntime  E  at android.os.Looper.loop(Looper.java:131)
AndroidRuntime  E  at android.app.ActivityThread.main(ActivityThread.java:5696)
AndroidRuntime  E  at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime  E  at java.lang.reflect.Method.invoke(Method.java:372)
AndroidRuntime  E  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
AndroidRuntime  E  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

Discussions on StackOverflow:
* http://stackoverflow.com/questions/26664922/crash-material-design-android-5-0/27906489
* http://stackoverflow.com/questions/26626344/scene-transition-with-hero-elements-throws-layer-exceeds-max-dimensions-support

**Comment by hidroh** [comment]
Pending for response to this Android bug before proceeding with fix https://code.google.com/p/android/issues/detail?id=167551

**Comment by AmolHegana** [comment]
I got same issue in Android Marshmallow in Xamarin forms development. You can get sample from https://forums.xamarin.com/discussion/64459/layer-exceeds-max-dimensions-supported-by-the-gpu-in-twintech-scroll-view-on-android-marshmallow


Please let me know if you have any solution to this. Scenario to simulate the crash 
1. Launch app in android-marshmallow
2. Click on Performance 3

App crashes with same error log.
Thanks in advance
