### ISSUE TITLE
No keyboard when hitting share button

### ISSUE THREAD

**Issue by cdysthe** [hidroh/materialistic#632]
When hitting a Twitter share button in an article viewed within the app I am not getting a keyboard  my keyboard works as normal otherwise

**Comment by hidroh** [comment]
Are you expecting keyboard to automatically show up in Twitter app? If you tap on text input in Twitter app does the keyboard show up? Are you sharing from internal browser (page with 3 tabs) or from custom Chrome tab?

**Comment by cdysthe** [comment]
It isn't in the twitter app l, its when I click a story in Materialistic.  The web page opens in Materialistic. When that page has a Twitter share button and I click it mobile Twitter opens inside Materialistic but there's no keyboard opening to log into mobile Twitter. I guess I can use the Materialistic share inatead of the page buttons

**Comment by hidroh** [comment]
Oh yeah it doesn't work that way. I cannot intercept share buttons within the webpage. If you want to share better press the share button provided by Materialistic, it will give you option to choose which app to share to, then when you choose Twitter it will redirect to Twitter app with you already logged in (given you install Twitter app).

**Comment by hidroh** [comment]
I'm gonna close this as there is no actionable item for me to work on.
