### ISSUE TITLE
Comment load crash

### ISSUE THREAD

**Issue by lwis** [hidroh/materialistic#654]
I can consistently reproduce a crash;

1. Open app
2. Press the comment shortcut on a post
3. Wait for load
4. Go back
5. Press the comment shortcut on the same post (or any others)
6. Crash 👎 

Let me know if there's anything else I can do to further help.

**Comment by hidroh** [comment]
Is this some thing you only notice recently after an update? Can you provide some extra information like app version (latest one is 3.0), and device information like model and Android version (e.g. Android 6 - Marshmallow, or Android 5 - Lollipop...). I understand that at step 4 the previous load has not finished before you hit back?

**Comment by lwis** [comment]
I started on the current play store version, I've tried a fresh install
also and I just built the current master copy - all exhibit the issue.

I've got a Nexus 5X running 7.0.

The comments finish loading before I press back.

**Comment by hidroh** [comment]
Strange, I have the same device + OS, couldn't reproduce it or see any relevant crash log. Are you able to access logcat? It would be a great help if you can provide the crash log so I can narrow down the issue. A `logcat *:S AndroidRuntime:E` command would give you the crash log.

**Comment by lwis** [comment]
@hidroh hmm, doesn't seem to capture anything. I'll take a closer look now to see if I can get you anything.

**Comment by lwis** [comment]
@hidroh http://pastebin.com/kwBt5ict

**Comment by hidroh** [comment]
Thanks!

So I spotted 2 lines that are related. It's the first time I see such error though so I need to dig into it.

```
09-04 14:21:08.562   873  3133 E InputDispatcher: channel 'b5a34b5 io.github.hidroh.materialistic/io.github.hidroh.materialistic.ListActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
09-04 14:21:08.565   873  3133 E InputDispatcher: channel 'da20968 io.github.hidroh.materialistic/io.github.hidroh.materialistic.ItemActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
```

**Comment by lwis** [comment]
@hidroh brilliant, thanks 👍

**Comment by lwis** [comment]
@hidroh any news on this, bud?

**Comment by lwis** [comment]
Actually, nevermind. This appears to be fixed in 3.1.

**Comment by hidroh** [comment]
Yay I actually didn't have time to check this 😁

**Comment by lwis** [comment]
Haha, the app is usable for me again! Good work buddy :)
