### ISSUE TITLE
When saving a story, mark it as a favorite

### ISSUE THREAD

**Issue by BrandTurner** [hidroh/materialistic#709]
I just assumed that saving a story would make it a favorite. When I save a story, I want to read it at a later time. I assumed that saving would also favorite.

Worse yet, I recently had to flash my phone and lost all my saved stories :(

**Comment by hidroh** [comment]
Saving a story will add it to 'Saved stories' as well as downloading it for offline access. Is it what you expect? If you mean 'Favorite' as in HN web then it's not supported at the moment.

Sorry saved stories currently do not persist across device update, unless you're on Android 6+ and set it up with Google account. This has been reported in #422

**Comment by hidroh** [comment]
Merged into #538
