### ISSUE TITLE
Export Saved stories as email attachment

### ISSUE THREAD

**Issue by orakle** [hidroh/materialistic#724]
App is crashing when tried exporting my saved stories via email, I currently have more than 10k saved stories...

**Comment by hidroh** [comment]
That's a lot of stories for my over simplified implementation. I guess I'll need to change it to write to a file as attachment.

**Comment by orakle** [comment]
that is true, for the last few months your app has become my bookmark store and made me use at least for few hours in a day, thanks for your wonderful contribution to the FOSS community.

**Comment by hidroh** [comment]
[`Intent.EXTRA_STREAM`](https://developer.android.com/reference/android/content/Intent.html#EXTRA_STREAM) can be used for file attachment.

**Comment by hidroh** [comment]
Another idea is to rely on DownloadManager to save export file to Downloads and let users choose what to do with it.

**Comment by hidroh** [comment]
@orakle I have published a new version of the app to Play Store that allows exporting saved stories as a file, which you can choose to upload to services like Google Drive or send via email as attachment. It should reach your device soon if you use Play Store version. Please check it out and let me know if you encounter issues.

**Comment by orakle** [comment]
@hidroh you are my hero, updated to the latest version... and it works like a charm. BIG thanks buddy!!!
