### ISSUE TITLE
Status bar icons change color when opening three-dot menu

### ISSUE THREAD

**Issue by Sparkesix** [hidroh/materialistic#764]
This also affects post's three-dot menu. I know it's not that big of a deal, just wanted to let you know.
[Gif of it.](http://gph.is/2fV4rbK)(giphy)
[Nexus 5X]

**Comment by hidroh** [comment]
Hi are you using stock Android or custom ROM? From the status bar it looks like you are not using the stock one (I also use Nexus 5X and couldn't reproduce this)

**Comment by Sparkesix** [comment]
Hey, yeah, that didn't occur to me that it could be the problem. I'm using PureNexus ROM. Sorry for this then.
