### ISSUE TITLE
Easy path to open in browser

### ISSUE THREAD

**Issue by mderazon** [hidroh/materialistic#784]
The article browser renderer is not so good. Scrolling is not smooth and lot of websites with JS don't render well and don't show at all.

Opening the article link opens it in a chrome Web view thing. Make it open in real browser instead, that chrome webview is not great either.

**Comment by hidroh** [comment]
Hi there, in Settings/Display, you can:
- turn on Use external browser
- turn off Use custom Chrome tab
The app will prompt you to choose which external browser to open when you choose an article.

**Comment by mderazon** [comment]
Awesome, thanks!
