### ISSUE TITLE
Sharing an article becomes default action for materialistic

### ISSUE THREAD

**Issue by ricka** [hidroh/materialistic#798]
When sharing either the article or the hacker news link, the action then becomes the default action for sharing in materialistic.  I'm having to go into applications and clear out my defaults for that application in order to change which action I choose for sharing every time I share something if I want to use a different app (sometimes I share to text, sometimes to pocket, sometimes to email, etc).

Samsung Galaxy S7

**Comment by hidroh** [comment]
I did make change to share, switching to platform share dialog. It should prompt to make an app default receiver for a shared link 'just once' or 'always'. Do you see similar dialog when you share?

![content- 2f 2fcom google android apps gsa velvet extradex staticpluginhostprovider 2fassist com google android apps gsa staticplugins assist screenshot screenshotprovider 2fcom google android apps gsa staticplugins assist screenshot screens](https://cloud.githubusercontent.com/assets/1978015/21070164/35dc506c-bebc-11e6-9aaf-720fe2fe9880.png)

**Comment by ricka** [comment]
It turns out this is a Samsung thing that removes the choice for sharing to Just Once or Always.  It also turns out that they recently rolled out another option to restore this functionality in Settings 》Applications 》Default applications 》Default application selection 》"Ask before setting default apps"
