### ISSUE TITLE
Always use in-app browser for Ask HN posts

### ISSUE THREAD

**Issue by Plastix** [hidroh/materialistic#832]
Hey @hidroh,

I'm curious what your thoughts are for including a text post at the top of the comments page. It would be really nice to see the OP along with the comments. I dislike that I have to open the article view if I want to see the post. Ideally, the app should hide the article view for a post that goes back to HN and display the post with comments. 

I'd be down to work on this feature and submit a PR.

**Comment by hidroh** [comment]
For one thing I think it would be confusing to users who are already used to HN web interface. Another UI issue would be all the replies would have to shift right to honour the hierarchy display, which wastes space.

I assume we're talking about posts such as Ask HN here? Are you using in-app browser? If so article view is just a swipe away. But if not then I can see what you're talking about. I think we can add article view for Ask HN posts, even for users that opt for external browser, as in this case it only renders and not making an external web request.

**Comment by Plastix** [comment]
I'm referring to HN text posts like Ask HN. Any HN post that has a text "body". For example:
<img width="1053" alt="screen shot 2017-01-09 at 4 36 31 pm" src="https://cloud.githubusercontent.com/assets/1526881/21784520/ee9aef3e-d689-11e6-924f-31ef2130a970.png">

I'm using an external browser + chrome custom tabs for viewing articles. I really feel like the post body should be native in the app.

**Comment by hidroh** [comment]
Yes it's native and display on a tab that you can swipe back and forth, but only if you enable in-app browser. I think we can solve it by forced enabling in-app browser for Ask HN posts.

**Comment by Plastix** [comment]
It is native? I have the in-app browser selected and I don't see any option for it:
![screenshot_20170109-210307](https://cloud.githubusercontent.com/assets/1526881/21791187/2af3844e-d6af-11e6-8f64-e2b2a20e3c30.png)

**Comment by hidroh** [comment]
You need to uncheck use external browser.

**Comment by Plastix** [comment]
Ah..so you can only see the post body if you use the in-app browser. I prefer to use external chrome custom tabs and not webviews for viewing articles.

**Comment by hidroh** [comment]
Yeah, but Ask HN is kind of a special post, it has both web page and a post body ready to display. So I think it makes sense enable in-app browser view for it, even if you choose external browser. Of course ext browser is still there for others kind of post.
