### ISSUE TITLE
Bug: The navigation button disappears if repositioned and on a device without navbar (with hardware buttons)

### ISSUE THREAD

**Issue by ric2b** [hidroh/materialistic#842]
Steps to reproduce:

0. Use a device without navbar/soft-touch buttons (i.e. hardware buttons for back, home and change app. If I go to the Android settings and enable the soft-touch buttons this bug stops immediatly, I don't even need to restart the app)
1. Activate on-screen navigation for materialistic
2. Re-position the navigation button (otherwise it works perfectly, but I hate the default position because scrolling down makes me hit the home button quite often.)
3. Open a random story's comments, go back to stories list, repeat multiple times (or different stories, doesn't matter). There is no discernible pattern but sometimes the navigation button will appear and sometimes it won't. After about 3 to 5 attempts it will almost certainly have disappeared at least once already.

Devices I have tested already:
- A BQ M5 Marshmallow phone with hardware buttons that allows me to disable or enable soft buttons
- An older KitKat phone with hardware buttons, but that does not allow me to enable the navbar
- A Nexus 7 with Marshmallow which has no hardware buttons and so does not let me disable the navbar
- A Jelly Bean phone which has no hardware buttons and so does not let me disable the navbar

With any of those four devices, if there is a navbar the bug does not happen, if there is no navbar, the bug does happen.

If you want any help tracking down this bug please let me know, I love the application and this seems like a very interesting bug, I have no idea what it could be :p

**Comment by hidroh** [comment]
Thanks for very detailed report! I'll try to schedule some time in future to look at it, but there are bigger issues/features that need to work on first currently.

**Comment by ric2b** [comment]
Hey, just updated to the latest version and it seems to be fixed, great! :)
Since no one else complained I'll close the issue.
Thank you for your great work!
