### ISSUE TITLE
windowBackground in LauncherActivity 

### ISSUE THREAD

**Issue by Harlber** [hidroh/materialistic#854]
https://developer.android.com/topic/performance/launch-time.html#  in 'Solutions to the problem' section

**Comment by hidroh** [comment]
Is there an issue with app launching time?

**Comment by Harlber** [comment]
It do exist in another low-configuration cellphone.In my opinion, this may become a feature just like Youtube's launch action.

**Comment by hidroh** [comment]
Current LauncherActivity has `Theme.NoDisplay`, which has no window background, and it simply redirects to other screens. I don't see any delay here if it does practically nothing?
