### ISSUE TITLE
Floating Navigation Button corner case

### ISSUE THREAD

**Issue by ShikherVerma** [hidroh/materialistic#866]
There is a corner case in the usage of Floating Navigation Button.  
In the video below I swipe right to show the replies to the second last comment.  
Then I swipe down to the last comment.  
Now on swiping right the replies aren't shown most probably because `linearLayoutManger.findFirstVisibleItemPosition()` would still be returning the position of the reply to the second last comment.

![ezgif-1-54e970a5bf](https://cloud.githubusercontent.com/assets/10194699/24317409/c1c5236c-111c-11e7-976b-3f50d08a78db.gif "Animated Explaination")

Btw awesome app. Works flawlessly!!

**Comment by hidroh** [comment]
Thanks for reporting, yes it's a known issue and I already have a TODO for it.
