### ISSUE TITLE
Bulk action to refresh selected saved stories

### ISSUE THREAD

**Issue by victorhooi** [hidroh/materialistic#882]
It would be nice if there was a way to refresh, or re-download saved stories, to get the latest updates (e.g. to comments).

**Comment by hidroh** [comment]
I think you can pull to refresh it same way as normal stories? For the article you can go fullscreen (using the floating button on bottom right), then hit refresh.

**Comment by victorhooi** [comment]
It would be nice if there was a way to refresh all though?

The use case for this is:

1. I'm currently about to hop on a flight - I'd like some Hacker News articles/comments to read on the plane - and it'd be nice to be able to hit a button to refresh everything just before I lose cellular data/Wi-Fi. I'm sure there are other situations (e.g. subway) or travelling to places with no I
2. I'm actually in Nepal - the internet here is quite flakey - as are the wi-fi AP's I'm connecting to. Materialistic seems to either keep stalling when downloading articles, or else it seems to just silently abort some downloads.
It'd be nice if there was a way to basically force everything to download again, to make sure it was all downloaded OK (or if there's some easter egg or other diagnostic trick to get network logs to see why articles are just not downloading etc.).

The hacky workaround I was using before was to go down the list of Saved Stories, swipe each to delete it, then Undo to save them again.

But if there was a simple menu option "Refresh All" that would be awesome =).

**Comment by hidroh** [comment]
Yeah i see your point, maybe i can do it as a multi select action, e.g. select saved stories you want to refresh, then choose option to refresh those. Refresh all would be quite costly as some users have hundreds or more saved stories.

**Comment by victorhooi** [comment]
Yup, I agree - having it as a bulk action makes much more sense (either ticking multiple stories, and/or allowing some kind of drag-select).

I've also noticed there's a way to export Saved Stories - but didn't see any provision to import that file?

Also - I couldn't find any way to sync my Saved Stories to the cloud.

Are these two features ones you're already aware of? Or would you like me to file Feature Requests for them as well?

**Comment by victorhooi** [comment]
Yup, I agree - having it as a bulk action makes much more sense (either ticking multiple stories, and/or allowing some kind of drag-select).

I've also noticed there's a way to export Saved Stories - but didn't see any provision to import that file?

Also - I couldn't find any way to sync my Saved Stories to the cloud.

Are these two features ones you're already aware of? Or would you like me to file Feature Requests for them as well?

**Comment by hidroh** [comment]
Yeah it's requested #538. Still trying to figure out how to do it without needing backend support. Exporting right now is just sort of like FYI kind of thing rather than meant to be used for import.

**Comment by victorhooi** [comment]
Yeah, I think a backend is probably going to be required....

I added some comments on #538 (basically suggesting Google Drive's AppData feature, or the Firebase realtime database) - feel free to reach out if you have any questions about either or need to ask anything at all - will try to answer myself, or happy to find somebody who can help.

**Comment by hidroh** [comment]
@victorhooi the option will be available on top (bulk) and as a swipe action
