### ISSUE TITLE
"Use external browser" setting ignored.

### ISSUE THREAD

**Issue by alopecoid** [hidroh/materialistic#89]
Even with the "Use external browser" setting selected, some internal browser that is "Powered by Chrome" is launched to display article content. This internal browser then has an option to "Open in Chrome".

This happens even when selecting the "View in external browser" icon and then selecting "Article".

Furthermore, selecting the "View in external browser" icon and then selecting "Comments" just reopens Materialistic.

Nexus 5
Android 6.0, build MRA58K
Materialistic 1.6

**Comment by hidroh** [comment]
Hi, for the first issue, that's Chrome custom tab, it's sort of a blend between Chrome browser and app. I'll make an option in setting to allow changing this.

For second issue you probably set Materialistic as default app to handle Hacker News hyperlinks. I'll try to make a fix to bypass this and allow opening Hacker News hyperlinks in external browser.

**Comment by alopecoid** [comment]
Wow, thanks for the quick fixes! Everything seems to be working as expected now. I will report back if I encounter any issues with the fixes.
