### ISSUE TITLE
Enhancement: allow for in-app PDF viewing/download

### ISSUE THREAD

**Issue by roumenguha** [hidroh/materialistic#918]
I understand if you don't want to implement this, but it would be cool if I could read linked PDFs inside the app instead of having to download it in another app like Chrome, or Xodo.

**Comment by hidroh** [comment]
We can have limited support for it for Android 5+ since it has API support.

**Comment by hidroh** [comment]
Sorry I'm closing this as I don't have capacity to implement this.
