### ISSUE TITLE
Edit posted comment

### ISSUE THREAD

**Issue by Symbian9** [hidroh/materialistic#931]
Is there a way how edit posted comment in Materialistic?

> https://news.ycombinator.com/item?id=14802901
> 
> If your post is <1hr old you can edit it for little clarifications like this :-)

I still can't find the way how do that in Materialistic

**Version**: 3.1 (74)

**Android**: 6.0

**Comment by hidroh** [comment]
Sorry it's not supported at the moment.

**Comment by tasmo** [comment]
@hidroh Is this because of the API?
