### ISSUE TITLE
Clarify difference btwn "best" vs "top" stories

### ISSUE THREAD

**Issue by therobinkim** [hidroh/materialistic#956]
As an infrequent Hacker News reader, I'm not sure if best vs top story is something determine by HN or if it's determined by Materialistic. Nonetheless, I think it would be helpful to clarify what the difference is as I have to pick between the two for my desktop widget!

Thanks for the awesome app. 😀

**Comment by hidroh** [comment]
Best is the same as https://news.ycombinator.com/best and top is https://news.ycombinator.com/. I don't know the exact difference but my understanding is that top is more real time while best seems to summarize the top stories in a longer time range.
