### ISSUE TITLE
Open links in chrome custom tabs

### ISSUE THREAD

**Issue by choyg** [hidroh/materialistic#969]
Links and URLs in the hn comment thread currently launch external browser but we could offer the option to fire an intent to chrome custom tabs (since it's already being used with 'View in External Browser')

**Comment by choyg** [comment]
Was wondering if you'd be open to a PR for this. If so, I'd love to try to contribute.

**Comment by hidroh** [comment]
Ah yes sorry I miss this. Let me try to open a PR for this I think it should be straightforward.

**Comment by choyg** [comment]
Thanks! Much appreciated.
