### ISSUE TITLE
Doesn't work from China

### ISSUE THREAD

**Issue by geokon-gh** [hidroh/materialistic#989]
The HN website works just fine from mainland China, but the Materialistic app doesnt work at all for some reason. Maybe it relies on fetching something from Google? (like JavaScript)

Let me know if I can help debug this

**Comment by hidroh** [comment]
The app uses Hacker News API (https://github.com/hackernews/api), which uses Firebase, which is now Google, so I suspect that's maybe why you can't access it?

**Comment by geokon-gh** [comment]
Gotcha. Guess the issue isn't on your end then. Well nothing to do I guess but just use the website directly :)
Thanks for the feedback nonetheless
